# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842e00b2de64fa8e17d05a187375e69bd626df902c5d2f80bc43b477f721131b427caec13bc1fb8da54302abba2dcfa21006536afd21ca76883926c2379b272d
  twitter_consumer_key: twitter_consumer_key
  twitter_consumer_secret: twitter_consumer_secret
  twitter_access_token: twitter_access_token
  twitter_access_token_secret: twitter_access_token_secret

test:
  secret_key_base: 0d807ad8c0a462a319b159f921a27121e9356a69d308bb6d6872aa7e9689e53cfaf4c5a8556e36c48c4e5325ff86ca720575b70821d36a0cd650921b7632002c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
